### ISSUE TITLE
Dual Extruder tool change leaving uneeded blemishes

### ISSUE THREAD

**Issue by HE3DUser151** [deathbybandaid/SpiceBot#1277]
Using dual extruder when the gcode T0 or T1 is entered, the printer moves the new nozzle to the position the inactive nozzle just finished printing. As the new nozzle often has the smallest amount of ooze, it drops this on the spot the last nozzle just finished causing colour bleed.
Would it be possible to adjust the position of the new nozzle using a translation of the first move it needs to go to instead of making the correction and then moving to the next position?
There would be two benefits of this, the first would be cleaner prints. The second would be faster overall print times because often when nozzle 2 moves to nozzle 1 location in a T1 move it often moves away from the location it needs to go to in the next gcode for motion.
Thanks!
The attached photo shows a small red line on the white cube from when a layer on the white completed, the nozzle with the red filament first moves to that location and then back to the location of the red cube to start printing.
![img_7584](https://user-images.githubusercontent.com/34404309/37388215-86e6800e-2757-11e8-9c96-88bbcaf903c5.jpg)

**Comment by Berserkir-Wolf** [comment]
Hi @HE3DUser151, 
I'm fairly sure this is not the repo you're looking for. This seems more like a question for the Lulzbot community - this repository is to do with an IRC chat bot built on the Sopel framework, not a 3D printer.
As for dual nozzle extrusion, I've not seen a clean solution for this yet. I believe that the new firmware on Makerbot Replicator 2x units allows for filament retraction to reduce extrusion drip/crosstalk, but I've not tested it myself - I currently only have access to a Replicator 2.

If you can read the GCode yourself you could potentially code a head move to the alternate side of the model and then have it translate back from there, but I tend to avoid custom GCode. I'll stick to Python and C#.
