### ISSUE TITLE
Complete OPT out

### ISSUE THREAD

**Issue by deathbybandaid** [deathbybandaid/SpiceBot#1308]
create a `.spicebot opt out` command that completely opts out.

add to the prerun to check if the entire input string contains any of the nicks in that array

that way ALL modules including .claim will output a privmsg saying "nick does NOT want to use the bot"

**Comment by Berserkir-Wolf** [comment]
We'll need to ensure that it runs whether or not the user has ruin .spicebot on

**Comment by deathbybandaid** [comment]
correct,,, just needs to check if rycuda is in the input string,,, then not allow the command

**Comment by josh-cunning** [comment]
the person running the command is still going to ping whoever but taking the bot out of the ping would be a good start.  I have all been thinking we have this sort of problem with commands that allow for non-user targets like blame
Searching every input for keywords sounds like it would slow things down a lot.

**Comment by Berserkir-Wolf** [comment]
This would be after someone gets into the channel and introduced to the bot. 
They could then run the optout command if they decide the bot is annoying. 
I vote that this command is a per-channel thing. Don't want the bot (unless rycuda, because valid reasons etc), opt out in SW and stay out of the bot channel. 
Something like the following?

````
foreach user in optedoutarray:
    if user in triggerargsarray:
        return baduser
````

**Comment by josh-cunning** [comment]
Could improve the target check command in Spicebotshared to also check that new array as well

**Comment by Berserkir-Wolf** [comment]
I'd put the code in both that and the prerun.
Prerun is probably a better idea, as it would stop code going further than it needs to before rejecting.

**Comment by Berserkir-Wolf** [comment]
And instead of returning baduser I'd make the return bool "leavethemalone"
Then "if not leavethemalone, carry on"

**Comment by josh-cunning** [comment]
The prerun already has the full input array so seems easy enough to search string for opted user.
