### ISSUE TITLE
Duels Classes Evaluate

### ISSUE THREAD

**Issue by deathbybandaid** [deathbybandaid/SpiceBot#1635]
Strength, Perception, Endurance, Charisma, Intelligence, Agility and Luck.

what should max be?

**Comment by deathbybandaid** [comment]
## blacksmith
## barbarian
## mage
## scavenger
## rogue
## ranger
## fiend
## vampire
## knight
## paladin

**Comment by deathbybandaid** [comment]
# Races

**Comment by josh-cunning** [comment]
I think having a race and class is overkill...just stick with class like setup. don't want to racist and type class people :)
Blacksmith needs to have really large armor boost to be balanced....maybe always start with armor? Fiend also seems pretty weak

**Comment by josh-cunning** [comment]
for max special stat it should be based on XP level...start each one at 10 max and add a point to each every spice XP levels. Also give the option to re-roll stats but does a full reset include XP amount

**Comment by josh-cunning** [comment]
If we stick with Class each one should have a plus and bad stat
Human - higher base health/higher potion worth more --no health regen or slower regen
barbarian - higher damage/rage -- cannot use magic
fiend - cannot use potions or magic but immune to both
vampire is good has you have it.
Then your class/race combo would mean more

**Comment by josh-cunning** [comment]
also while I am thinking about it special should only apply to only to class choice. Before setting numbers need to figure out what each stat is going to effect. What ideas do you have for each stat?

**Comment by deathbybandaid** [comment]
thief class has a chance of a five-finger discount when buying/trading

**Comment by deathbybandaid** [comment]
duels when rebalancing classes,,, make a class that has a lower stamin cost

**Comment by deathbybandaid** [comment]
Duels Class: "Featherweight". Take a 10% reduction in damage dealt in return for 25% more stamina

**Comment by deathbybandaid** [comment]
When adding species, each should have pro/con.

Troll:

Resilient
Cannot have other people use healthpotions on them (error message: "do not feed the trolls")

**Comment by deathbybandaid** [comment]
deathbybandaid requested: duels Ranger class should be a High Chance of keeping your loot upon death, instead of guaranteed...

**Comment by deathbybandaid** [comment]
endurance should be what makes the maximum bodypart health

**Comment by deathbybandaid** [comment]
SPECIAL-like stats like agility that are class-based. agility could help when dodging grenades,,,, could be pretty creative

**Comment by deathbybandaid** [comment]
done
