### ISSUE TITLE
askmeabout

### ISSUE THREAD

**Issue by deathbybandaid** [deathbybandaid/SpiceBot#400]
This is an interesting idea I had

people can submit to a database array, the things they are good at talking about

.askmeabout add Plex

.askmeabout add Proxmox

then have a command that people can run to query if anybody has something listed

example, I'm new to proxmox, and want to know who can help me with something, and talk it through

I would run .askmeabout proxmox

and the script would do something like:

````
personarray
skill = trigger.group(2)
for u in users-in-the-channel:
    skillsarray = get_database_array('askmeabout')
    if skill in skillsarray:
         personarray.append(u)
bot.say(str(personarray))
````

**Comment by Berserkir-Wolf** [comment]
elif "I don't know anyone knowledgeable about that".

**Comment by Berserkir-Wolf** [comment]
Help.py
import sopel.module
import sys
import os
moduledir = os.path.dirname(__file__)
sys.path.append(moduledir)
from SpicebotShared import *

@sopel.module.commands('help','helpwith','helpfrom','skill') #not sure about the last
def mainfunction(bot, trigger):
    enablestatus, triggerargsarray = spicebot_prerun(bot, trigger)
    if not enablestatus:
        execute_main(bot, trigger, triggerargsarray)
    
def execute_main(bot, trigger, triggerargsarray):
    commandused = trigger.group(1)
    option = trigger.group(2)
    target = trigger.group(2)
if not target
    target = instigator

if commandused == help
-if not option, bot.say (wikilink)
-elif option
--if option == duel, bot.say (duelwikilink)
--if option == spicebucks, bot.say (spicebuckwikilink)
-- option == lottery,weather,spin etc...

if commandused==skill
if option == add (add skill to db against target)
if option == show(show skills listed against target)
if option == list(show all skills in db [remove duplicates?])

if commandused == helpwith
check db for option, if found return "you could ask " + nick_from_db " about that"
if not found, return "I don't know anyone who can help with that yet"

if commandused == helpfrom
success = 0
if not option
 target = instigator
 success = 1
if option in channel users array
target = option
success = 1

if success = 1
     check db for target nick. If found list skills.
     if not found, return "nick has no special skills listed"
elif success = 0
bot.say (I'm sorry, I don't know who that is)

**Comment by Berserkir-Wolf** [comment]
Thought - if the nick being checked is not online, should the query still complete? Or should  it only check for whitespace and reject the nick if found?

**Comment by Berserkir-Wolf** [comment]
Add to halp_not_help, rename to 'halp'

**Comment by deathbybandaid** [comment]
I like the idea of being able to tag people with skills,,,, but there may need to be abuse-prevention,,,

I could tag you as tree-hugger, and you would have to remove it

maybe a database value for suggested tags,,, and a command to approve them

**Comment by Berserkir-Wolf** [comment]
I'm thinking this can be my next project - knock this part out. 
Make it so that only self can add tags, but could have a tag suggest call .tell somehow and say "instigator suggested you add x to skillsarray"

**Comment by deathbybandaid** [comment]
steal the code from weaponslocker?

````
helpfulusers = []
for user in channel:
    skillsetarray = get_db_value
    if skilltofind in skillsetarray:
        helpfulusers.append(user)
if helpfulusers != []:
    listofusers = triggerargs('list')
    bot.say("These users may know something about " + skilltofind + ": " + listofusers)
````

whatcha think @Berserkir-Wolf

**Comment by Berserkir-Wolf** [comment]
Maybe. I'm kinda over this idea, we get enough dumb questions without giving people a way to target them at us.
I've barely got time for the wiki lately.
