### ISSUE TITLE
SpiceWorks_IRC_Rules.py

### ISSUE THREAD

**Issue by Berserkir-Wolf** [deathbybandaid/SpiceBot#429]
Add full rulesofinternet (rulesofinternet.com) list
Respond to rulenumber (subrules like 9.1, 10c etc need converting to same scheme and listing with startswith)

Idea only

**Comment by Berserkir-Wolf** [comment]
Migrate channel rules to spicebot_user - .spicebot rule/rules (int) for channel rules.
change .rule to internet rules.

**Comment by Berserkir-Wolf** [comment]
https://raw.githubusercontent.com/deathbybandaid/sopel-modules/dev/otherfiles/rules_of_internet.txt

**Comment by deathbybandaid** [comment]
I like the idea, but I like the simplicity of the .rules command right now,,,

I am also considering moving .warn back into it's own module

**Comment by Berserkir-Wolf** [comment]
Makes sense. Rules of internet is low priority. Would be extraneous given the amount of times we would actually use it.
