### ISSUE TITLE
Module counter

### ISSUE THREAD

**Issue by Berserkir-Wolf** [deathbybandaid/SpiceBot#430]
Create a counter in spicebotshared to track module usage levels.

**Comment by Berserkir-Wolf** [comment]
For channel counts:
adjust_botdatabase_value(bot, channel, str(commandused + "usage"), 1)

For individual counts:
adjust_botdatabase_value(bot, trigger.nick, str(commandused + "usage"), 1)

Add to Spicebotshared somewhere around L79.

**Comment by Berserkir-Wolf** [comment]
Add usage module - 
.usage 'command' 'target'
if target in channelusers, get_database_value(bot, target, 'usage')
if target == channel, get_database_value(bot, botchannel, 'usage')

if usage == 0, bot.say(that command does not appear to have been used)

**Comment by Berserkir-Wolf** [comment]
Usage counters in spicebotshared added

**Comment by Berserkir-Wolf** [comment]
Usage check commands added

**Comment by Berserkir-Wolf** [comment]
adjust_botdatabase_value(bot, botchannel, str(commandused + "usage"), 1) ## Channel usage of specific module
adjust_botdatabase_value(bot, botchannel, "spicebotusage", 1) ## Channel usage of bot overall
adjust_botdatabase_value(bot, trigger.nick, str(commandused + "usage"), 1) ## User usage of specific module
adjust_botdatabase_value(bot, trigger.nick, "spicebotusage", 1) ## User usage of bot overall

**Comment by Berserkir-Wolf** [comment]
dysonparkes found an issue: usage needs to be adjusted to be usage module target only, no usage target. set if module inchannel reply invalid. if module total then totalcount.

**Comment by Berserkir-Wolf** [comment]
Spicebot_admin gone, add option to spicebot.py

**Comment by Berserkir-Wolf** [comment]
Add to new prerun method

**Comment by deathbybandaid** [comment]
the new prerun is ready for this to be added back in

**Comment by Berserkir-Wolf** [comment]
I'll resume developing the .usage function
Might be worth adding a totalusage command to spicebotadmin as well - could be defined in usage.py and imported.

**Comment by deathbybandaid** [comment]
I made a new issue, closing this one
