### ISSUE TITLE
know your meme

### ISSUE THREAD

**Issue by deathbybandaid** [deathbybandaid/SpiceBot#506]
http://knowyourmeme.com/

**Comment by Berserkir-Wolf** [comment]
Could migrate googleit to a 'search' module - tie .gif, .google, .googleit, .youtube, .meme into one module.

def searchroutine(baseurl, query) - .google would use a google base url, urlencode it, and pass the urlencoded string as query.

**Comment by Berserkir-Wolf** [comment]
https://github.com/deathbybandaid/SpiceBot/issues/460
