### ISSUE TITLE
Casino bank/jackpots

### ISSUE THREAD

**Issue by josh-cunning** [deathbybandaid/SpiceBot#517]
I want to have a jackpot that builds as more people gamble. What are your thoughts on having this pull other fees like taxes? 
Also everything else seemed to be tied to a specific user/nick...would we need to give funds to bot or create a new user?

**Comment by deathbybandaid** [comment]
give the extra funds to bot.nick, or switch the nick value with spicebank

**Comment by josh-cunning** [comment]
Casino games are now setup to use the Spicebank for funds. It defaults to generate the cash if funds aren't in the spicebank. Jack pot pays the full spicebank balance or 500 which ever is greater. 
Collect taxes also dump into the SpiceBank.
