### ISSUE TITLE
Duels Megathread! (for features, not issues)

### ISSUE THREAD

**Issue by deathbybandaid** [deathbybandaid/SpiceBot#629]
I'm going to combine duel ideas that I intend to implement into a single thread.

**Comment by deathbybandaid** [comment]
I will edit this comment as I go. Please make suggestions and comments below this one.

Todo:

* Classes are great, have great advantages, but maybe they should also have disadvantages

Done:

* tons of shit

**Comment by deathbybandaid** [comment]
This comment will serve as my personal changelog

**Comment by Berserkir-Wolf** [comment]
Check [this feature](https://github.com/deathbybandaid/SpiceBot/projects/1) to see if that might be easier than combining threads each time. Drag card into project instead of merging threads, then each issue/feature can be closed independently.

**Comment by Berserkir-Wolf** [comment]
Note - close/reopen was to test automation

**Comment by deathbybandaid** [comment]
going to uncombine to use the project page
