### ISSUE TITLE
DUELS: class that can retaliate ocasionally

### ISSUE THREAD

**Issue by deathbybandaid** [deathbybandaid/SpiceBot#659]
Class Idea: class that can retaliate ocasionally

**Comment by deathbybandaid** [comment]
still think this would be cool

**Comment by Berserkir-Wolf** [comment]
Agreed. Maybe a diceroll for "lucky shot in return" that's worth half the damage or 20, whichever is lower.

**Comment by deathbybandaid** [comment]
created a new class "knight"
