### ISSUE TITLE
Wiki Update: Update the wiki to include the timeout settings

### ISSUE THREAD

**Issue by josh-cunning** [deathbybandaid/SpiceBot#710]
I think the timeout for using channel commands is pretty straight forward but it would be nice to have it written down somewhere.  Also would be nice to have a baseline of what duel timeouts are.

**Comment by Berserkir-Wolf** [comment]
@josh-cunning, what page do you think would be most logical for these to be on?
Main timeouts in [Using the Bot](https://github.com/deathbybandaid/SpiceBot/wiki/Using-the-Bot), duel timeouts in [Duels](https://github.com/deathbybandaid/SpiceBot/wiki/Duels)?
